# APEX Configuration

# Minimum profit threshold (as a decimal, e.g., 0.001 = 0.1%)
minProfitThreshold: 0.001

# Trading pairs to monitor across exchanges
tradingPairs:
  - baseCurrency: BTC
    quoteCurrency: USDT
  - baseCurrency: ETH
    quoteCurrency: USDT
  - baseCurrency: SOL
    quoteCurrency: USDT

# Exchange-specific configurations
exchanges:
  binance:
    enabled: true
    takerFee: 0.001  # 0.1%
  
  kraken:
    enabled: true
    takerFee: 0.0026  # 0.26%
  
  coinbase:
    enabled: false
    takerFee: 0.006  # 0.6%

# Logging configuration
logging:
  level: info
  file: data/arbitrage.log
  format: text

# Opportunities tracking
opportunities:
  logFile: data/opportunities.csv
  logFormat: csv